version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: it-concat
    versions:
    - 2.0.0
  - dependency-name: ipfsd-ctl
    versions:
    - 8.0.0
    - 8.0.1
  - dependency-name: it-reader
    versions:
    - 3.0.0
  - dependency-name: it-to-stream
    versions:
    - 1.0.0
  - dependency-name: aegir
    versions:
    - 33.0.0
  - dependency-name: multihashes
    versions:
    - 4.0.1
  - dependency-name: ipfs
    versions:
    - 0.53.2
    - 0.54.0
    - 0.54.1
